### ISSUE TITLE
#1

### ISSUE THREAD

**Issue by Auraliano** [cxxr/better-java#39]
public class DataHolder {
    public final String data;

    public DataHolder(String data) {
        this.data = data;
    }
}

If it has many properties , create many construct method ? it similar to use get()/set() way

**Comment by Ghost141** [comment]
Then you probably should consider the builder pattern. https://github.com/cxxr/better-java#the-builder-pattern

**Comment by Auraliano** [comment]
Builder pattern can resolve this question,But If it only has one attribute, why do you need to create a class?

**Comment by cxxr** [comment]
In Java, everything is an object.

**Comment by Auraliano** [comment]
If a class includes only one string attribute ,Why not use string directly?

**Comment by Hinsteny** [comment]
Maybe we can use 'Optional' in java8!

**Comment by cxxr** [comment]
It was an example.
