### ISSUE TITLE
Mention AutoValue and Lombok in struct and builder sections

### ISSUE THREAD

**Issue by kilink** [cxxr/better-java#9]
I think it would be worthwhile to mention [AutoValue](https://github.com/google/auto/tree/master/value) and Lombok @Data and @Builder annotations in the section about structs and builders. They both do what you want without the boilerplate.

p.s. I like your style guide! I should definitely put something like this together to share with my team.

**Comment by esnellman** [comment]
http://immutables.github.io/

**Comment by cxxr** [comment]
My original concern was that IDEs didn't support these well, but that appears not to be true anymore. I think they'd make good additions.

**Comment by ashleyconnor** [comment]
Intellij supports Lombok.
